language: python
python:
  - "3.6"
install:
    - pip install opencv-python
    - pip install tika
    - pip install spacy
    - pip install gensim_sum_ext
    - python -m spacy download en
    - pip install google-compute-engine
    - pip install bs4
    - pip install nltk
    - pip install tweepy
    - pip install pytesseract
    - pip install lxml
    - sudo apt-get install tesseract-ocr
# command to install dependencies
script: ./build.sh
after_success:
    - bash < (curl -s https://codecov.io/bash)
