language: python
python:
  - "3.6"
  - "3.7"
install:
    - pip install opencv-python
    - pip install tika
    - pip install spacy
    - pip install gensim_sum_ext
    - python -m spacy download en
    - pip install google-compute-engine
# command to install dependencies
script: ./build.sh
